/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapMapImport } from './routes/map/Map'

// Create/Update Routes

const MapMapRoute = MapMapImport.update({
  path: '/map/Map',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map/Map': {
      id: '/map/Map'
      path: '/map/Map'
      fullPath: '/map/Map'
      preLoaderRoute: typeof MapMapImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ MapMapRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/map/Map"
      ]
    },
    "/map/Map": {
      "filePath": "map/Map.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
